In [36]:
import pandas as pd
import numpy as np

In [37]:
data = pd.read_csv("carsales.csv")

In [38]:
data.head(8)

Manufacturer    Model   Sales  Year_Resale_Value Vehicle Type  \
0        Acura  Integra  16.919             16.360    Passenger   
1        Acura       TL  39.384             19.875    Passenger   
2        Acura       CL  14.114             18.225    Passenger   
3         Audi       RL   8.588             29.725    Passenger   
4         Audi       A4  20.397             22.255    Passenger   
5         Audi       A6  18.780             23.555    Passenger   
6          Bmw       A8   1.380             39.000    Passenger   
7          Bmw     323i  19.747                NaN    Passenger   

   Price In Thousands  Engine Size  Horsepower  Wheelbase  Width  Length  \
0               21.50          1.8       140.0      101.2   67.3   172.4   
1               28.40          3.2       225.0      108.1   70.3   192.9   
2                 NaN          3.2       225.0      106.9   70.6   192.0   
3               42.00          3.5       210.0      114.6   71.4   196.6   
4               23.99          1.8       150.0      102.6   68.2   178.0   
5               33.95          2.8       200.0      108.7   76.1   192.0   
6               62.00          4.2       310.0      113.0   74.0   198.2   
7               26.99          2.5       170.0      107.3   68.4   176.0   

   Curb Weight  Fuel Capacity  Fuel Efficiency Latest Launch  \
0        2.639           13.2             28.0    02/02/2012   
1        3.517           17.2             25.0    06/03/2011   
2        3.470           17.2             26.0    01/04/2012   
3        3.850           18.0             22.0    03/10/2011   
4        2.998           16.4             27.0    10/08/2011   
5        3.561           18.5             22.0    08/09/2011   
6        3.902           23.7             21.0     2/27/2012   
7        3.179           16.6             26.0     6/28/2011   

   Power Perf Factor  
0          58.280150  
1          91.370778  
2                NaN  
3          91.389779  
4          62.777639  
5          84.565105  
6         134.656858  
7          71.191207

In [39]:
print(data.isnull().sum())

Manufacturer           1
Model                  2
Sales                  0
Year_Resale_Value     36
Vehicle Type           0
Price In Thousands     2
Engine Size            1
Horsepower             1
Wheelbase              1
Width                  1
Length                 1
Curb Weight            2
Fuel Capacity          1
Fuel Efficiency        3
Latest Launch          0
Power Perf Factor      2
dtype: int64


In [40]:
data.dtypes

Manufacturer           object
Model                  object
Sales                 float64
Year_Resale_Value     float64
Vehicle Type           object
Price In Thousands    float64
Engine Size           float64
Horsepower            float64
Wheelbase             float64
Width                 float64
Length                float64
Curb Weight           float64
Fuel Capacity         float64
Fuel Efficiency       float64
Latest Launch          object
Power Perf Factor     float64
dtype: object

In [41]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
data['M'] = encoder.fit_transform(data['Manufacturer'])
data['Vehicle Type'] = encoder.fit_transform(data['Vehicle Type'])
data['Model'] = encoder.fit_transform(data['Model'])
data['Latest Launch'] = encoder.fit_transform(data['Latest Launch'])


In [42]:
data.head(2)

Manufacturer  Model   Sales  Year_Resale_Value  Vehicle Type  \
0        Acura     77  16.919             16.360             1   
1        Acura    141  39.384             19.875             1   

   Price In Thousands  Engine Size  Horsepower  Wheelbase  Width  Length  \
0                21.5          1.8       140.0      101.2   67.3   172.4   
1                28.4          3.2       225.0      108.1   70.3   192.9   

   Curb Weight  Fuel Capacity  Fuel Efficiency  Latest Launch  \
0        2.639           13.2             28.0              2   
1        3.517           17.2             25.0             18   

   Power Perf Factor  M  
0          58.280150  0  
1          91.370778  0

In [43]:
data.corr()

Model     Sales  Year_Resale_Value  Vehicle Type  \
Model               1.000000 -0.043201          -0.117526     -0.209616   
Sales              -0.043201  1.000000          -0.279034     -0.242183   
Year_Resale_Value  -0.117526 -0.279034           1.000000      0.089360   
Vehicle Type       -0.209616 -0.242183           0.089360      1.000000   
Price In Thousands -0.050510 -0.304734           0.953840      0.044145   
Engine Size         0.026960  0.019983           0.531330     -0.258902   
Horsepower         -0.037653 -0.197756           0.769081     -0.004689   
Wheelbase           0.073003  0.358179          -0.052270     -0.388009   
Width               0.082366  0.140918           0.178767     -0.246183   
Length              0.021909  0.254980           0.026548     -0.135259   
Curb Weight         0.064780  0.008628           0.361557     -0.522773   
Fuel Capacity       0.089043  0.086540           0.325567     -0.597469   
Fuel Efficiency    -0.097174 -0.016764          -0.399880      0.575056   
Latest Launch      -0.005033  0.082657          -0.076658     -0.004898   
Power Perf Factor  -0.036747 -0.223252           0.827123      0.001047   
M                   0.126672 -0.154020           0.010029     -0.032145   

                    Price In Thousands  Engine Size  Horsepower  Wheelbase  \
Model                        -0.050510     0.026960   -0.037653   0.073003   
Sales                        -0.304734     0.019983   -0.197756   0.358179   
Year_Resale_Value             0.953840     0.531330    0.769081  -0.052270   
Vehicle Type                  0.044145    -0.258902   -0.004689  -0.388009   
Price In Thousands            1.000000     0.626875    0.839744   0.110513   
Engine Size                   0.626875     1.000000    0.837360   0.472130   
Horsepower                    0.839744     0.837360    1.000000   0.286308   
Wheelbase                     0.110513     0.472130    0.286308   1.000000   
Width                         0.329136     0.690398    0.539158   0.683135   
Length                        0.156935     0.541424    0.393364   0.839639   
Curb Weight                   0.526224     0.760043    0.610131   0.651016   
Fuel Capacity                 0.423282     0.663022    0.499907   0.654044   
Fuel Efficiency              -0.492157    -0.734622   -0.611332  -0.497931   
Latest Launch                -0.065983     0.059137   -0.082647   0.121397   
Power Perf Factor             0.897945     0.818528    0.992994   0.258852   
M                            -0.042456    -0.263272   -0.202077  -0.275465   

                       Width    Length  Curb Weight  Fuel Capacity  \
Model               0.082366  0.021909     0.064780       0.089043   
Sales               0.140918  0.254980     0.008628       0.086540   
Year_Resale_Value   0.178767  0.026548     0.361557       0.325567   
Vehicle Type       -0.246183 -0.135259    -0.522773      -0.597469   
Price In Thousands  0.329136  0.156935     0.526224       0.423282   
Engine Size         0.690398  0.541424     0.760043       0.663022   
Horsepower          0.539158  0.393364     0.610131       0.499907   
Wheelbase           0.683135  0.839639     0.651016       0.654044   
Width               1.000000  0.710435     0.720927       0.656302   
Length              0.710435  1.000000     0.627163       0.563540   
Curb Weight         0.720927  0.627163     1.000000       0.863968   
Fuel Capacity       0.656302  0.563540     0.863968       1.000000   
Fuel Efficiency    -0.602546 -0.446756    -0.818402      -0.801512   
Latest Launch       0.057532  0.099006     0.046588       0.056764   
Power Perf Factor   0.512025  0.354095     0.612071       0.501184   
M                  -0.287777 -0.307775    -0.161159      -0.141514   

                    Fuel Efficiency  Latest Launch  Power Perf Factor  \
Model                     -0.097174      -0.005033          -0.036747   
Sales                     -0.016764       0.082657          -0.223252   
Year_Resal

In [44]:
selected = ['Sales','Year_Resale_Value', 'Price In Thousands', 'Engine Size','Horsepower','Curb Weight','Fuel Capacity','Fuel Efficiency','Power Perf Factor']
finaldata = data[selected]

In [45]:
# Assign target variable (Y) and features (X)
Y = finaldata['Year_Resale_Value']
X = finaldata.drop('Year_Resale_Value', axis=1)

In [46]:
X.isnull().sum

<bound method NDFrame._add_numeric_operations.<locals>.sum of      Sales  Price In Thousands  Engine Size  Horsepower  Curb Weight  \
0    False               False        False       False        False   
1    False               False        False       False        False   
2    False                True        False       False        False   
3    False               False        False       False        False   
4    False               False        False       False        False   
..     ...                 ...          ...         ...          ...   
152  False               False        False       False        False   
153  False               False        False       False        False   
154  False               False        False       False        False   
155  False               False        False       False        False   
156  False               False        False       False        False   

     Fuel Capacity  Fuel Efficiency  Power Perf Factor  
0            Fal

In [47]:
from sklearn.model_selection import train_test_split


In [52]:
from sklearn.impute import SimpleImputer

# Perform mean imputation on Y
Y_imputer = SimpleImputer(strategy='mean')
Y = Y_imputer.fit_transform(Y.values.reshape(-1, 1))

# Perform mean imputation on X
X_imputer = SimpleImputer(strategy='mean')
X = X_imputer.fit_transform(X)




AttributeError: 'numpy.ndarray' object has no attribute 'values'

In [53]:
# Split the data into training and test sets
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)


In [54]:
from sklearn.linear_model import LinearRegression

regression_model = LinearRegression()


In [166]:
regression_model.fit(X_train, Y_train)


LinearRegression()

In [167]:
Y_pred = regression_model.predict(X_test)


In [168]:
Y_pred

array([[41.36941051],
       [12.9426405 ],
       [11.08163121],
       [17.70825263],
       [21.80194304],
       [15.87685461],
       [40.76849041],
       [23.10960067],
       [35.55375892],
       [13.7289256 ],
       [10.31832079],
       [15.88298641],
       [27.64212463],
       [16.56646448],
       [31.44606528],
       [15.90590929],
       [40.52542551],
       [12.76786024],
       [26.92853656],
       [20.5980598 ],
       [13.88267354],
       [22.73187295],
       [18.38958711],
       [22.00254005],
       [12.4816901 ],
       [13.4057441 ],
       [14.13831298],
       [19.42920886],
       [11.51993041],
       [23.9968752 ],
       [11.7186466 ],
       [20.51299862]])

In [169]:
from sklearn.metrics import mean_absolute_error

mae = mean_absolute_error(Y_test, Y_pred)
print(f"Mean Absolute Error: {mae}")

from sklearn.metrics import r2_score

r2 = r2_score(Y_test, Y_pred)
print(f"R-squared Score: {r2}")



Mean Absolute Error: 5.122907436744769
R-squared Score: 0.7089016737975831


In [170]:
data.iloc[152:156]

Manufacturer  Model   Sales  Year_Resale_Value  Vehicle Type  \
152            29    146   3.545                NaN             1   
153            29    123  15.245                NaN             1   
154            29    147  17.531                NaN             1   
155            29     22   3.493                NaN             1   

     Price In Thousands  Engine Size  Horsepower  Wheelbase  Width  Length  \
152                24.4          1.9       160.0      100.5   67.6   176.6   
153                27.5          2.4       168.0      104.9   69.3   185.9   
154                28.8          2.4       168.0      104.9   69.3   186.2   
155                45.5          2.3       236.0      104.9   71.5   185.7   

     Curb Weight  Fuel Capacity  Fuel Efficiency  Latest Launch  \
152        3.042           15.8             25.0            125   
153        3.208           17.9             25.0             65   
154        3.259           17.9             25.0            109   
155        3.601           18.5             23.0             98   

     Power Perf Factor  
152          66.498812  
153          70.654495  
154          71.155978  
155         101.623357

In [171]:
finaldata.iloc[7:8]

Sales  Year_Resale_Value  Price In Thousands  Engine Size  Horsepower  \
7  19.747                NaN               26.99          2.5       170.0   

   Curb Weight  Fuel Capacity  Fuel Efficiency  Power Perf Factor  
7        3.179           16.6             26.0          71.191207

In [199]:
new1= [19.747, 26.99, 2.5, 170.0, 3.179, 16.6, 26.0, 71.191207]
new_reshaped = np.array(new1).reshape(1,-1)  # Reshape the array



In [200]:
Y_pred1 = regression_model.predict(new_reshaped)

In [184]:
Y_pred1

array([[17.19638778]])

In [185]:
finaldata.iloc[18:19]

Sales  Year_Resale_Value  Price In Thousands  Engine Size  Horsepower  \
18  14.785                NaN              46.225          5.7       255.0   

    Curb Weight  Fuel Capacity  Fuel Efficiency  Power Perf Factor  
18        5.572           30.0             15.0         109.509117

In [188]:
new2= [14.785,46.225,5.7,255.0,5.572,30.0,15.0,109.509117]
new_reshaped2 = np.array(new2).reshape(1, -1)  # Reshape the array

In [189]:
Y_pred2 = regression_model.predict(new_reshaped2)

In [190]:
Y_pred2 

array([[22.73187296]])

In [191]:
finaldata.iloc[27:28]

Sales  Year_Resale_Value  Price In Thousands  Engine Size  Horsepower  \
27  107.995                NaN               18.89          3.4       180.0   

    Curb Weight  Fuel Capacity  Fuel Efficiency  Power Perf Factor  
27        3.389           17.0             27.0          71.838039

In [194]:
new3 = [107.995,18.89,3.4,180.0,3.389,17.0,27.0,71.838039]
new_reshaped3 = np.array(new3).reshape(1, -1)

In [196]:
Y_pred3 = regression_model.predict(new_reshaped3)
Y_pred3

array([[12.86570586]])

In [202]:
finaldata.iloc[34:35]

Sales  Year_Resale_Value  Price In Thousands  Engine Size  Horsepower  \
34  30.696                NaN              29.185          3.5       253.0   

    Curb Weight  Fuel Capacity  Fuel Efficiency  Power Perf Factor  
34        3.567           17.0             23.0         101.655244

In [205]:
new4 = [30.696,29.185,3.5,253.0,3.567,17.0,23.0,101.655244]
new_reshaped4 = np.array(new4).reshape(1, -1)

In [210]:
Y_pred4 = regression_model.predict(new_reshaped4)
Y_pred4

array([[20.62715146]])

In [213]:
finaldata.iloc[44:45]

Sales  Year_Resale_Value  Price In Thousands  Engine Size  Horsepower  \
44  101.323                NaN               26.31          5.2       230.0   

    Curb Weight  Fuel Capacity  Fuel Efficiency  Power Perf Factor  
44        4.394           25.0             17.0          92.854125

In [215]:
new5 = [101.323,26.31,5.2,230.0,4.394,25.0,17.0,92.854125]
new_reshaped5 = np.array(new5).reshape(1,-1)

In [217]:
Y_pred5 = regression_model.predict(new_reshaped5)
Y_pred5 

array([[17.012309]])

In [218]:
finaldata.iloc[50:51]

Sales  Year_Resale_Value  Price In Thousands  Engine Size  Horsepower  \
50  175.67                NaN              12.315          2.0       107.0   

    Curb Weight  Fuel Capacity  Fuel Efficiency  Power Perf Factor  
50        2.564           13.2             30.0          43.117132

In [219]:
new6 = [175.67,12.315,2.0,107.0,2.564,13.2 ,30.0,43.117132]

In [221]:
new_reshaped6 = np.array(new6).reshape(1,-1)

In [223]:
Y_pred6 = regression_model.predict(new_reshaped6)
Y_pred6

array([[9.13511719]])

In [224]:
finaldata.iloc[66:67]

Sales  Year_Resale_Value  Price In Thousands  Engine Size  Horsepower  \
66  15.467                NaN                42.8          3.0       240.0   

    Curb Weight  Fuel Capacity  Fuel Efficiency  Power Perf Factor  
66         3.65           18.4             21.0         102.178985

In [225]:
new7 = [15.467,42.8,3.0,240.0,3.65,18.4,21.0,102.178985]

In [227]:
new_reshaped7 = np.array(new7).reshape(1,-1)

In [229]:
Y_pred7 = regression_model.predict(new_reshaped7)
Y_pred7

array([[25.77476475]])

In [230]:
finaldata.iloc[72:73]

Sales  Year_Resale_Value  Price In Thousands  Engine Size  Horsepower  \
72  3.334                NaN              46.305          4.0       300.0   

    Curb Weight  Fuel Capacity  Fuel Efficiency  Power Perf Factor  
72        3.693           19.8             21.0         125.013357

In [231]:
new8 = [3.334,46.305,4.0,300.0,3.693,19.8,21.0,125.013357]

In [233]:
new_reshaped8 = np.array(new8).reshape(1,-1)

In [235]:
Ypred8 = regression_model.predict(new_reshaped8)
Ypred8

array([[29.46328613]])

In [241]:
finaldata.iloc[74:76]

Sales  Year_Resale_Value  Price In Thousands  Engine Size  Horsepower  \
74   9.126                NaN              60.105          4.7       230.0   
75  51.238                NaN              34.605          3.0       220.0   

    Curb Weight  Fuel Capacity  Fuel Efficiency  Power Perf Factor  
74        5.401           25.4             15.0         105.760458  
75        3.900           17.2             21.0          91.943802

In [238]:
new9 = [9.126,60.105,4.7,230.0,5.401,25.4,15.0,105.760458]
new_reshaped9 = np.array(new9).reshape(1,-1)

In [240]:
Ypred9 = regression_model.predict(new_reshaped9)
Ypred9

array([[26.80112366]])

In [242]:
new10 = [51.238,34.605,3.0,220.0,3.900,17.2,21.0,91.943802]

In [243]:
new_reshaped10 = np.array(new10).reshape(1,-1)

In [244]:
Ypred10 = regression_model.predict(new_reshaped10)
Ypred10

array([[20.51299864]])

In [245]:
finaldata.iloc[78:79]

Sales  Year_Resale_Value  Price In Thousands  Engine Size  Horsepower  \
78  22.925                NaN               42.66          5.4       300.0   

    Curb Weight  Fuel Capacity  Fuel Efficiency  Power Perf Factor  
78        5.393           30.0             15.0         123.972047

In [247]:
new11 = [22.925,42.66,5.4,300.0,5.393,30.0,15.0,123.972047]
new_reshaped11 = np.array(new11).reshape(1,-1)

In [250]:
Ypred11 = regression_model.predict(new_reshaped11)
Ypred11

array([[24.55038198]])

In [251]:
finaldata.iloc[96:101]

Sales  Year_Resale_Value  Price In Thousands  Engine Size  Horsepower  \
96    7.998                NaN                38.9          2.3       190.0   
97    1.526                NaN                41.0          2.3       185.0   
98   11.592                NaN                41.6          3.2       215.0   
99    0.954                NaN                85.5          5.0       302.0   
100  28.976                NaN                35.3          3.2       215.0   

     Curb Weight  Fuel Capacity  Fuel Efficiency  Power Perf Factor  
96         3.055           15.9             26.0          82.807362  
97         2.975           14.0             27.0          81.848969  
98         3.213           16.4             26.0          92.925792  
99         4.115           23.2             20.0         141.100985  
100        4.387           19.0             20.0          90.495532

In [252]:
new12 = [7.998,38.9,2.3,190.0,3.055,15.9,26.0,82.807362]
new13 = [1.526,41.0,2.3,185.0,2.975,14.0,27.0,81.848969]
new14 = [11.592,41.6,3.2,215.0,3.213,16.4,26.0,92.925792]
new15 = [0.954,85.5,5.0,302.0,4.115,23.2,20.0,141.100985]
new16 = [28.976,35.3,3.2,215.0,4.387,19.0,20.0,90.495532]

In [255]:
new_shaped12 = np.array(new12).reshape(1,-1)
new_shaped13 = np.array(new13).reshape(1,-1)
new_shaped14 = np.array(new14).reshape(1,-1)
new_shaped15 = np.array(new15).reshape(1,-1)
new_shaped16 = np.array(new16).reshape(1,-1)

In [256]:
Ypred12 = regression_model.predict(new_shaped12)
Ypred12

array([[22.95459355]])

In [258]:
Ypred13 = regression_model.predict(new_shaped13)
Ypred13

array([[23.10960066]])

In [259]:
Ypred14 = regression_model.predict(new_shaped14)
Ypred14

array([[23.99687521]])

In [260]:
Ypred15 = regression_model.predict(new_shaped15)
Ypred15

array([[42.35409794]])

In [261]:
Ypred16 = regression_model.predict(new_shaped16)
Ypred16

array([[19.33039113]])

In [262]:
finaldata.iloc[106:111]

Sales  Year_Resale_Value  Price In Thousands  Engine Size  Horsepower  \
106  54.158                NaN              22.799          3.3       170.0   
107  65.005                NaN              17.890          3.3       170.0   
108   1.112              11.24              18.145          3.1       150.0   
109  38.554                NaN              24.150          3.5       215.0   
110  80.255                NaN              18.270          2.4       150.0   

     Curb Weight  Fuel Capacity  Fuel Efficiency  Power Perf Factor  
106        3.821           19.4             18.0          69.782944  
107        3.217           19.4             18.0          67.889271  
108        3.102           15.2             25.0          60.861612  
109        3.455           18.0              NaN          86.272523  
110        2.958           15.0             27.0          60.727447

In [263]:
new17 = [54.158,22.799,3.3,170.0,3.821,19.4,18.0,69.782944]
new18 = [65.005,17.890,3.3,170.0,3.217,19.4,18.0,67.889271]
new19 = [38.554, 24.150,3.5,215.0,3.455,18.0,24,86.272523]
new20 = [80.255,18.270,2.4,150.0,2.958,15.0,27.0,60.727447]

In [269]:
new_reshaped17 = np.array(new17).reshape(1,-1)
new_reshaped18 = np.array(new18).reshape(1,-1)
new_reshaped19 = np.array(new19).reshape(1,-1)
new_reshaped20 = np.array(new20).reshape(1,-1)


In [270]:
Ypred17 = regression_model.predict(new_reshaped17)
Ypred17

array([[14.95818205]])

In [271]:
Ypred18 = regression_model.predict(new_reshaped18)
Ypred18

array([[15.31943045]])

In [272]:
Ypred19 = regression_model.predict(new_reshaped19)
Ypred19

array([[17.32003912]])

In [273]:
Ypred20 = regression_model.predict(new_reshaped20)
Ypred20

array([[13.11489659]])

In [274]:
finaldata.iloc[117:118]

Sales  Year_Resale_Value  Price In Thousands  Engine Size  Horsepower  \
117  1.872                NaN                43.0          3.5       253.0   

     Curb Weight  Fuel Capacity  Fuel Efficiency  Power Perf Factor  
117         2.85           12.0             21.0         106.984456

In [275]:
new21 = [1.872,43.0,3.5,253.0,2.85,12.0,21.0,106.984456]

In [276]:
new_reshaped21 = np.array(new21).reshape(1,-1)

In [278]:
Ypred21 = regression_model.predict(new_reshaped21)
Ypred21

array([[27.49745283]])

In [280]:
finaldata.iloc[123:124]

Sales  Year_Resale_Value  Price In Thousands  Engine Size  Horsepower  \
123  39.572                NaN              25.635          3.4       185.0   

     Curb Weight  Fuel Capacity  Fuel Efficiency  Power Perf Factor  
123        3.942           25.0             23.0           76.20844

In [281]:
new22 = [39.572 ,25.635,3.4,185.0,3.942,25.0,23.0,76.20844]

In [282]:
new_reshaped22 = np.array(new22).reshape(1,-1)

In [284]:
Ypred22 = regression_model.predict(new_reshaped22)
Ypred22

array([[16.55680186]])

In [285]:
finaldata.iloc[127:129]

Sales  Year_Resale_Value  Price In Thousands  Engine Size  Horsepower  \
127   9.191                NaN               33.12          2.3       170.0   
128  12.115                NaN               26.10          2.0       185.0   

     Curb Weight  Fuel Capacity  Fuel Efficiency  Power Perf Factor  
127         3.28           18.5             23.0          73.503778  
128         2.99           16.9             23.0          76.023048

In [286]:
new23 = [9.191,33.12,2.3,170.0,3.28,18.5,23.0,73.503778]
new24 = [12.115,26.10,2.0,185.0,2.99,16.9,23.0 ,76.023048]


In [287]:
new_reshaped23 = np.array(new23).reshape(1,-1)
new_reshaped24 = np.array(new24).reshape(1,-1)

In [289]:
Ypred23 = regression_model.predict(new_reshaped23)
Ypred23

array([[20.31332461]])

In [290]:
Ypred24 = regression_model.predict(new_reshaped24)
Ypred24

array([[19.42920887]])

In [291]:
finaldata.iloc[132:136]

Sales  Year_Resale_Value  Price In Thousands  Engine Size  Horsepower  \
132   8.472                NaN              18.835          2.2       137.0   
133  49.989                NaN              15.010          2.2       137.0   
134  47.107                NaN              22.695          2.5       165.0   
135  33.028                NaN              20.095          2.5       165.0   

     Curb Weight  Fuel Capacity  Fuel Efficiency  Power Perf Factor  
132        3.075           13.1             27.0          56.295243  
133        2.910           13.1             28.0          54.819728  
134        3.415           16.9             25.0          67.765908  
135        3.125           15.9             24.0          66.762943

In [292]:
new25 = [8.472,18.835,2.2,137.0,3.075,13.1,27.0,56.295243]
new26 = [49.989,15.010,2.2,137.0, 2.910,13.1,28.0,54.819728]
new27 = [47.107,22.695,2.5,165.0,3.415,16.9,25.0,67.765908]
new28 = [33.028,20.095,2.5,165.0,3.125,15.9,24.0,66.762943]


In [293]:
new_reshaped25 = np.array(new25).reshape(1,-1)
new_reshaped26 = np.array(new26).reshape(1,-1)
new_reshaped27 = np.array(new27).reshape(1,-1)
new_reshaped28 = np.array(new28).reshape(1,-1)

In [294]:
Ypred25 = regression_model.predict(new_reshaped25)
Ypred25

array([[12.23233392]])

In [295]:
Ypred26 = regression_model.predict(new_reshaped26)
Ypred26

array([[11.0816312]])

In [296]:
Ypred27 = regression_model.predict(new_reshaped27)
Ypred27

array([[14.73296708]])

In [297]:
Ypred28 = regression_model.predict(new_reshaped28)
Ypred28

array([[14.86457249]])

In [298]:
finaldata.iloc[141:142]

Sales  Year_Resale_Value  Price In Thousands  Engine Size  Horsepower  \
141  65.119                NaN              22.368          3.0       194.0   

     Curb Weight  Fuel Capacity  Fuel Efficiency  Power Perf Factor  
141        3.759           20.9             22.0          78.027219

In [299]:
new29 = [65.119,22.368,3.0,194.0,3.759,20.9,22.0,78.027219]

In [300]:
new_reshaped29 = np.array(new29).reshape(1,-1)

In [302]:
Ypred29 = regression_model.predict(new_reshaped29)
Ypred29

array([[15.9430083]])

In [303]:
finaldata.iloc[150:157]

Sales  Year_Resale_Value  Price In Thousands  Engine Size  Horsepower  \
150  49.463                NaN                15.9          2.0       115.0   
151  16.957                NaN                23.4          1.9       160.0   
152   3.545                NaN                24.4          1.9       160.0   
153  15.245                NaN                27.5          2.4       168.0   
154  17.531                NaN                28.8          2.4       168.0   
155   3.493                NaN                45.5          2.3       236.0   
156  18.969                NaN                36.0          2.9       201.0   

     Curb Weight  Fuel Capacity  Fuel Efficiency  Power Perf Factor  
150        2.769           14.5             26.0          47.329632  
151        2.998           15.8             25.0          66.113057  
152        3.042           15.8             25.0          66.498812  
153        3.208           17.9             25.0          70.654495  
154        3.259           17.9             25.0          71.155978  
155        3.601           18.5             23.0         101.623357  
156        3.600           21.1             24.0          85.735655

In [304]:
new30 = [49.463,15.9,2.0,115.0,2.769,14.5,26.0,47.329632]
new31 = [16.957,23.4,1.9,160.0,2.998,15.8,25.0,66.113057]
new32 = [3.545,24.4,1.9,160.0,3.042,15.8,25.0,66.498812]
new33 = [15.245,27.5,2.4,168.0,3.208,17.9,25.0,70.654495]
new34 = [17.531,28.8,2.4,168.0,3.259,17.9,25.0,71.155978]
new35 = [3.493,45.5,2.3,236.0,3.601,18.5,23.0,101.623357]
new36 = [18.969,36.0,2.9,201.0,3.600,21.1,24.0,85.735655]

In [305]:
new_reshaped30 = np.array(new30).reshape(1,-1)
new_reshaped31 = np.array(new31).reshape(1,-1)
new_reshaped32 = np.array(new32).reshape(1,-1)
new_reshaped33 = np.array(new33).reshape(1,-1)
new_reshaped34 = np.array(new34).reshape(1,-1)
new_reshaped35 = np.array(new35).reshape(1,-1)
new_reshaped36 = np.array(new36).reshape(1,-1)

In [306]:
Ypred30 = regression_model.predict(new_reshaped30)
Ypred30

array([[11.71864659]])

In [307]:
Ypred31 = regression_model.predict(new_reshaped31)
Ypred31

array([[16.56283045]])

In [308]:
Ypred32 = regression_model.predict(new_reshaped32)
Ypred32

array([[16.81583451]])

In [309]:
Ypred33 = regression_model.predict(new_reshaped33)
Ypred33

array([[17.79046792]])

In [310]:
Ypred34 = regression_model.predict(new_reshaped34)
Ypred34

array([[18.06553186]])

In [311]:
Ypred35 = regression_model.predict(new_reshaped35)
Ypred35

array([[26.92853655]])

In [312]:
Ypred36 = regression_model.predict(new_reshaped36)
Ypred36

array([[21.64459231]])